# Generated by Django 6.0.3 on 2026-04-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_preferred_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Professional biography and background'),
        ),
        migrations.AddField(
            model_name='user',
            name='board_position',
            field=models.CharField(blank=True, help_text='Specific position on the board', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='board_tenure_start',
            field=models.DateField(blank=True, help_text='Date when board tenure started', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.TextField(blank=True, help_text='Educational qualifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.TextField(blank=True, help_text='Professional experience'),
        ),
        migrations.AddField(
            model_name='user',
            name='expertise',
            field=models.TextField(blank=True, help_text='Areas of expertise'),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='other_credentials',
            field=models.TextField(blank=True, help_text='Other professional credentials and certifications'),
        ),
    ]
