# Generated by Django 6.0.3 on 2026-04-16 20:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_bio_user_board_position_user_board_tenure_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSOProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('provider_type', models.CharField(choices=[('okta', 'Okta'), ('azure_ad', 'Azure Active Directory'), ('google', 'Google Workspace'), ('auth0', 'Auth0'), ('keycloak', 'Keycloak'), ('ping', 'Ping Identity'), ('saml', 'Generic SAML'), ('oidc', 'Generic OIDC')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('testing', 'Testing')], default='disabled', max_length=20)),
                ('saml_entity_id', models.CharField(blank=True, help_text='Entity ID for SAML', max_length=255)),
                ('saml_sso_url', models.URLField(blank=True, help_text='SSO URL for SAML')),
                ('saml_slo_url', models.URLField(blank=True, help_text='SLO URL for SAML')),
                ('saml_certificate', models.TextField(blank=True, help_text='X.509 certificate')),
                ('saml_metadata_url', models.URLField(blank=True, help_text='Metadata URL')),
                ('oidc_client_id', models.CharField(blank=True, max_length=255)),
                ('oidc_client_secret', models.CharField(blank=True, max_length=255)),
                ('oidc_issuer_url', models.URLField(blank=True)),
                ('oidc_authorization_endpoint', models.URLField(blank=True)),
                ('oidc_token_endpoint', models.URLField(blank=True)),
                ('oidc_userinfo_endpoint', models.URLField(blank=True)),
                ('oidc_jwks_uri', models.URLField(blank=True)),
                ('email_attribute', models.CharField(default='email', help_text='Attribute name for email', max_length=100)),
                ('first_name_attribute', models.CharField(default='given_name', help_text='Attribute name for first name', max_length=100)),
                ('last_name_attribute', models.CharField(default='family_name', help_text='Attribute name for last name', max_length=100)),
                ('role_attribute', models.CharField(blank=True, help_text='Attribute name for role', max_length=100)),
                ('role_mapping', models.JSONField(blank=True, help_text='Map SSO roles to system roles', null=True)),
                ('auto_provision_users', models.BooleanField(default=True, help_text='Automatically create users on first login')),
                ('default_role', models.CharField(blank=True, help_text='Default role for auto-provisioned users', max_length=50)),
                ('require_encryption', models.BooleanField(default=True)),
                ('allowed_domains', models.TextField(blank=True, help_text='Comma-separated list of allowed email domains')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sso_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SSO Provider',
                'verbose_name_plural': 'SSO Providers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserSSOIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(help_text='External user ID from SSO provider', max_length=255)),
                ('external_username', models.CharField(blank=True, max_length=255)),
                ('external_email', models.EmailField(blank=True, max_length=254)),
                ('attributes', models.JSONField(blank=True, help_text='Additional attributes from SSO', null=True)),
                ('first_login', models.BooleanField(default=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_identities', to='accounts.ssoprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sso_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User SSO Identity',
                'verbose_name_plural': 'User SSO Identities',
                'ordering': ['-last_login_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ssoprovider',
            index=models.Index(fields=['provider_type', 'status'], name='accounts_ss_provide_11deca_idx'),
        ),
        migrations.AddIndex(
            model_name='ssoprovider',
            index=models.Index(fields=['status'], name='accounts_ss_status_0b87c7_idx'),
        ),
        migrations.AddIndex(
            model_name='userssoidentity',
            index=models.Index(fields=['user', 'provider'], name='accounts_us_user_id_7c4809_idx'),
        ),
        migrations.AddIndex(
            model_name='userssoidentity',
            index=models.Index(fields=['provider', 'external_id'], name='accounts_us_provide_c6396b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userssoidentity',
            unique_together={('provider', 'external_id')},
        ),
    ]
