# Generated by Django 6.0.3 on 2026-04-16 20:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_usersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptionKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Friendly name for the key', max_length=100)),
                ('key_type', models.CharField(choices=[('aes256', 'AES-256-GCM'), ('rsa4096', 'RSA-4096'), ('chacha20', 'ChaCha20-Poly1305')], default='aes256', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('rotating', 'Rotating'), ('deprecated', 'Deprecated'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('encrypted_key', models.TextField(help_text='Encrypted key material')),
                ('key_fingerprint', models.CharField(help_text='SHA-256 fingerprint of the key', max_length=64, unique=True)),
                ('rotation_interval_days', models.PositiveIntegerField(default=90, help_text='Days between key rotations')),
                ('last_rotated_at', models.DateTimeField(auto_now_add=True)),
                ('next_rotation_at', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_encryption_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Encryption Key',
                'verbose_name_plural': 'Encryption Keys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='accounts_en_status_68f40c_idx'), models.Index(fields=['key_type'], name='accounts_en_key_typ_266acf_idx'), models.Index(fields=['next_rotation_at'], name='accounts_en_next_ro_09ffa7_idx')],
            },
        ),
    ]
