# Generated by Django 6.0.3 on 2026-04-16 21:01

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_encryptionkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='ISO 639-1 language code (e.g., en, fr, sw)', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Language name in English', max_length=100)),
                ('native_name', models.CharField(help_text='Language name in the language itself', max_length=100)),
                ('locale_code', models.CharField(help_text='Locale code (e.g., en_US, fr_FR, sw_KE)', max_length=20)),
                ('direction', models.CharField(choices=[('ltr', 'LTR'), ('rtl', 'RTL')], default='ltr', max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('beta', 'Beta'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('translation_coverage', models.PositiveIntegerField(default=0, help_text='Percentage of strings translated', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('flag_emoji', models.CharField(blank=True, help_text='Flag emoji (e.g., 🇺🇸, 🇫🇷, 🇰🇪)', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='accounts_la_code_8c297f_idx'), models.Index(fields=['status'], name='accounts_la_status_abd16b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(help_text='Translation key (e.g., common.button.submit)', max_length=500)),
                ('context', models.CharField(blank=True, help_text='Context for the translation', max_length=200)),
                ('module', models.CharField(blank=True, help_text='Module/app this belongs to', max_length=100)),
                ('translations', models.JSONField(default=dict, help_text='Language code to translation mapping')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
                'ordering': ['key'],
                'indexes': [models.Index(fields=['key'], name='accounts_tr_key_848436_idx'), models.Index(fields=['module'], name='accounts_tr_module_12eb53_idx')],
            },
        ),
    ]
