# Generated by Django 6.0.3 on 2026-04-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_language_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(default='en', help_text='Your preferred language for the interface', max_length=10),
        ),
    ]
