# Generated by Django 6.0.3 on 2026-04-16 20:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentcomment_documentshare_documenttag_and_more'),
        ('meetings', '0007_quorumcheck'),
        ('messaging', '0001_initial'),
        ('voting', '0004_decisiondocumentation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('summary', models.CharField(blank=True, help_text='Brief summary for notifications', max_length=300)),
                ('target_audience', models.CharField(choices=[('all', 'All Users'), ('board_members', 'Board Members'), ('company_secretary', 'Company Secretary'), ('executive_management', 'Executive Management'), ('compliance_officer', 'Compliance Officer'), ('it_administrator', 'IT Administrator'), ('internal_audit', 'Internal Audit'), ('custom', 'Custom Selection')], default='all', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('publish_at', models.DateTimeField(blank=True, help_text='Schedule publication for future date', null=True)),
                ('expire_at', models.DateTimeField(blank=True, help_text='When to expire/unpublish the announcement', null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('attachments', models.ManyToManyField(blank=True, related_name='announcements', to='documents.document')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
                ('custom_targets', models.ManyToManyField(blank=True, help_text="Custom user selection when target_audience is 'custom'", related_name='targeted_announcements', to=settings.AUTH_USER_MODEL)),
                ('related_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='meetings.meeting')),
                ('related_motion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='voting.motion')),
                ('viewed_by', models.ManyToManyField(blank=True, related_name='viewed_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='messaging_a_status_0b098d_idx'), models.Index(fields=['priority', '-created_at'], name='messaging_a_priorit_b368d0_idx'), models.Index(fields=['publish_at'], name='messaging_a_publish_bf1d7b_idx'), models.Index(fields=['expire_at'], name='messaging_a_expire__18c7ac_idx')],
            },
        ),
    ]
