# Generated by Django 6.0.3 on 2026-04-16 20:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Friendly name for the API key', max_length=200)),
                ('key', models.CharField(help_text='API key value', max_length=255, unique=True)),
                ('prefix', models.CharField(default='eboard_', help_text='Key prefix for identification', max_length=10)),
                ('scope', models.CharField(choices=[('read', 'Read Only'), ('write', 'Read/Write'), ('admin', 'Admin')], default='read', max_length=20)),
                ('allowed_endpoints', models.JSONField(blank=True, help_text='List of allowed endpoint patterns', null=True)),
                ('denied_endpoints', models.JSONField(blank=True, help_text='List of denied endpoint patterns', null=True)),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=60, help_text='Requests per minute')),
                ('rate_limit_per_hour', models.PositiveIntegerField(default=1000, help_text='Requests per hour')),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('ip_whitelist', models.JSONField(blank=True, help_text='List of allowed IP addresses', null=True)),
                ('require_https', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys', to='agencies.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10)),
                ('endpoint', models.CharField(max_length=500)),
                ('query_params', models.JSONField(blank=True, null=True)),
                ('status_code', models.PositiveIntegerField()),
                ('response_status', models.CharField(choices=[('success', 'Success'), ('unauthorized', 'Unauthorized'), ('forbidden', 'Forbidden'), ('not_found', 'Not Found'), ('rate_limited', 'Rate Limited'), ('server_error', 'Server Error'), ('validation_error', 'Validation Error')], max_length=20)),
                ('response_time_ms', models.PositiveIntegerField(help_text='Response time in milliseconds')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('request_size', models.PositiveIntegerField(blank=True, help_text='Request body size in bytes', null=True)),
                ('response_size', models.PositiveIntegerField(blank=True, help_text='Response body size in bytes', null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to='api.apikey')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Request Log',
                'verbose_name_plural': 'API Request Logs',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('integration_type', models.CharField(choices=[('slack', 'Slack'), ('teams', 'Microsoft Teams'), ('salesforce', 'Salesforce'), ('hubspot', 'HubSpot'), ('zapier', 'Zapier'), ('custom', 'Custom Integration')], max_length=20)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error'), ('configuring', 'Configuring')], default='configuring', max_length=20)),
                ('configuration', models.JSONField(help_text='Integration-specific configuration')),
                ('credentials_encrypted', models.TextField(blank=True, help_text='Encrypted credentials')),
                ('callback_url', models.URLField(blank=True)),
                ('auto_sync', models.BooleanField(default=False)),
                ('sync_interval_minutes', models.PositiveIntegerField(default=60)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, max_length=50)),
                ('last_error', models.TextField(blank=True)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrations', to='agencies.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Integration',
                'verbose_name_plural': 'Integrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(help_text='Webhook URL to send events to')),
                ('events', models.JSONField(help_text='List of events to subscribe to')),
                ('secret', models.CharField(blank=True, help_text='HMAC secret for signature verification', max_length=255)),
                ('require_https', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('retry_on_failure', models.BooleanField(default=True)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('retry_delay_seconds', models.PositiveIntegerField(default=60)),
                ('custom_headers', models.JSONField(blank=True, help_text='Custom headers to send with webhook', null=True)),
                ('total_deliveries', models.PositiveIntegerField(default=0)),
                ('successful_deliveries', models.PositiveIntegerField(default=0)),
                ('failed_deliveries', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhooks', to='agencies.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webhook',
                'verbose_name_plural': 'Webhooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('event_data', models.JSONField(help_text='Event payload')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='api.webhook')),
            ],
            options={
                'verbose_name': 'Webhook Delivery',
                'verbose_name_plural': 'Webhook Deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['user', '-created_at'], name='api_apikey_user_id_1f0423_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['status'], name='api_apikey_status_88bfe1_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['key'], name='api_apikey_key_5dc959_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=models.Index(fields=['api_key', '-requested_at'], name='api_apirequ_api_key_c320c7_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=models.Index(fields=['user', '-requested_at'], name='api_apirequ_user_id_6c6431_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=models.Index(fields=['endpoint'], name='api_apirequ_endpoin_b6a911_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=models.Index(fields=['status_code'], name='api_apirequ_status__428601_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=models.Index(fields=['-requested_at'], name='api_apirequ_request_0860a3_idx'),
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['user', '-created_at'], name='api_integra_user_id_94fe0f_idx'),
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['status'], name='api_integra_status_8e0d46_idx'),
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['integration_type'], name='api_integra_integra_728083_idx'),
        ),
        migrations.AddIndex(
            model_name='webhook',
            index=models.Index(fields=['user', '-created_at'], name='api_webhook_user_id_b4d11b_idx'),
        ),
        migrations.AddIndex(
            model_name='webhook',
            index=models.Index(fields=['status'], name='api_webhook_status_07a6b8_idx'),
        ),
        migrations.AddIndex(
            model_name='webhook',
            index=models.Index(fields=['events'], name='api_webhook_events_482b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['webhook', '-created_at'], name='api_webhook_webhook_9ca5f3_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['status'], name='api_webhook_status_21baf4_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['event_type'], name='api_webhook_event_t_19ea33_idx'),
        ),
    ]
