# Generated by Django 6.0.3 on 2026-04-16 21:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('wcag_level', models.CharField(choices=[('a', 'Level A'), ('aa', 'Level AA'), ('aaa', 'Level AAA')], default='aa', max_length=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('target_url', models.URLField(help_text='URL or section being audited')),
                ('target_page', models.CharField(blank=True, help_text='Specific page or component name', max_length=200)),
                ('overall_compliance', models.CharField(choices=[('compliant', 'Compliant'), ('partially_compliant', 'Partially Compliant'), ('non_compliant', 'Non-Compliant'), ('not_tested', 'Not Tested')], default='not_tested', max_length=30)),
                ('compliance_score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('audit_method', models.CharField(blank=True, help_text='e.g., Automated scan, Manual review, User testing', max_length=100)),
                ('tools_used', models.JSONField(blank=True, help_text='List of accessibility testing tools used', null=True)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_issues', models.PositiveIntegerField(default=0)),
                ('critical_issues', models.PositiveIntegerField(default=0)),
                ('serious_issues', models.PositiveIntegerField(default=0)),
                ('moderate_issues', models.PositiveIntegerField(default=0)),
                ('minor_issues', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessibility_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accessibility Audit',
                'verbose_name_plural': 'Accessibility Audits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessibilityIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('wcag_criteria', models.CharField(blank=True, choices=[('1.1.1', 'Non-text Content'), ('1.2.1', 'Audio-only and Video-only (Prerecorded)'), ('1.2.2', 'Captions (Prerecorded)'), ('1.2.3', 'Audio Description or Media Alternative (Prerecorded)'), ('1.2.4', 'Captions (Live)'), ('1.2.5', 'Audio Description (Prerecorded)'), ('1.3.1', 'Info and Relationships'), ('1.3.2', 'Meaningful Sequence'), ('1.3.3', 'Sensory Characteristics'), ('1.3.4', 'Orientation'), ('1.3.5', 'Identify Input Purpose'), ('1.4.1', 'Use of Color'), ('1.4.2', 'Audio Control'), ('1.4.3', 'Contrast (Minimum)'), ('1.4.4', 'Resize text'), ('1.4.5', 'Images of Text'), ('1.4.10', 'Reflow'), ('1.4.11', 'Non-text Contrast'), ('1.4.12', 'Text Spacing'), ('1.4.13', 'Content on Hover or Focus'), ('2.1.1', 'Keyboard'), ('2.1.2', 'No Keyboard Trap'), ('2.1.4', 'Character Key Shortcuts'), ('2.2.1', 'Timing Adjustable'), ('2.2.2', 'Pause, Stop, Hide'), ('2.3.1', 'Three Flashes or Below'), ('2.3.2', 'Three Flashes'), ('2.4.1', 'Bypass Blocks'), ('2.4.2', 'Page Titled'), ('2.4.3', 'Focus Order'), ('2.4.4', 'Link Purpose (In Context)'), ('2.4.5', 'Multiple Ways'), ('2.4.6', 'Headings and Labels'), ('2.4.7', 'Focus Visible'), ('2.5.1', 'Pointer Gestures'), ('2.5.2', 'Pointer Cancellation'), ('2.5.3', 'Label in Name'), ('2.5.4', 'Motion Actuation'), ('3.1.1', 'Language of Page'), ('3.1.2', 'Language of Parts'), ('3.2.1', 'On Focus'), ('3.2.2', 'On Input'), ('3.2.3', 'Consistent Navigation'), ('3.2.4', 'Consistent Identification'), ('3.2.5', 'Change on Request'), ('3.3.1', 'Error Identification'), ('3.3.2', 'Labels or Instructions'), ('3.3.3', 'Error Suggestion'), ('3.3.4', 'Error Prevention (Legal, Financial, Data)'), ('3.3.5', 'Help'), ('4.1.1', 'Parsing'), ('4.1.2', 'Name, Role, Value'), ('4.1.3', 'Status Messages')], max_length=20)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('serious', 'Serious'), ('moderate', 'Moderate'), ('minor', 'Minor')], default='moderate', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('verified', 'Verified'), ('deferred', 'Deferred'), ('wont_fix', "Won't Fix")], default='open', max_length=20)),
                ('element_type', models.CharField(blank=True, help_text='e.g., Button, Form, Image, Link', max_length=100)),
                ('element_selector', models.CharField(blank=True, help_text='CSS selector for the element', max_length=500)),
                ('reproduction_steps', models.TextField(blank=True)),
                ('expected_behavior', models.TextField(blank=True)),
                ('actual_behavior', models.TextField(blank=True)),
                ('suggested_fix', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_accessibility_issues', to=settings.AUTH_USER_MODEL)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='accessibility.accessibilityaudit')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_accessibility_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accessibility Issue',
                'verbose_name_plural': 'Accessibility Issues',
                'ordering': ['-severity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessibilityRemediation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approach', models.TextField(help_text='Description of the remediation approach')),
                ('estimated_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('implementation_notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='remediation', to='accessibility.accessibilityissue')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_remediations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accessibility Remediation',
                'verbose_name_plural': 'Accessibility Remediations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='accessibilityaudit',
            index=models.Index(fields=['status', '-created_at'], name='accessibili_status_e4b018_idx'),
        ),
        migrations.AddIndex(
            model_name='accessibilityaudit',
            index=models.Index(fields=['wcag_level'], name='accessibili_wcag_le_299988_idx'),
        ),
        migrations.AddIndex(
            model_name='accessibilityaudit',
            index=models.Index(fields=['overall_compliance'], name='accessibili_overall_2c51ca_idx'),
        ),
        migrations.AddIndex(
            model_name='accessibilityaudit',
            index=models.Index(fields=['target_url'], name='accessibili_target__811ee5_idx'),
        ),
        migrations.AddIndex(
            model_name='accessibilityissue',
            index=models.Index(fields=['audit', '-created_at'], name='accessibili_audit_i_5a2445_idx'),
        ),
        migrations.AddIndex(
            model_name='accessibilityissue',
            index=models.Index(fields=['severity'], name='accessibili_severit_4042e6_idx'),
        ),
        migrations.AddIndex(
            model_name='accessibilityissue',
            index=models.Index(fields=['status'], name='accessibili_status_0c3158_idx'),
        ),
        migrations.AddIndex(
            model_name='accessibilityissue',
            index=models.Index(fields=['wcag_criteria'], name='accessibili_wcag_cr_efb3d0_idx'),
        ),
        migrations.AddIndex(
            model_name='accessibilityremediation',
            index=models.Index(fields=['issue'], name='accessibili_issue_i_74d43a_idx'),
        ),
        migrations.AddIndex(
            model_name='accessibilityremediation',
            index=models.Index(fields=['status'], name='accessibili_status_6f00fc_idx'),
        ),
        migrations.AddIndex(
            model_name='accessibilityremediation',
            index=models.Index(fields=['planned_end_date'], name='accessibili_planned_5ba89d_idx'),
        ),
    ]
