# Generated by Django 6.0.3 on 2026-04-16 17:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0004_meetingaction_alter_meetingattendance_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('zoom', 'Zoom'), ('teams', 'Microsoft Teams'), ('in_app', 'In-App Recording'), ('other', 'Other')], max_length=50)),
                ('platform_meeting_id', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('recording', 'Recording'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='recordings/audio/%Y/%m/%d/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='recordings/video/%Y/%m/%d/')),
                ('file_url', models.URLField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('auto_transcribe', models.BooleanField(default=True)),
                ('auto_summarize', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_recordings', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_recordings', to='meetings.meeting')),
            ],
            options={
                'db_table': 'meeting_recordings',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('context', models.TextField(blank=True, null=True)),
                ('timestamp_in_recording', models.FloatField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_action_items', to=settings.AUTH_USER_MODEL)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='recordings.meetingrecording')),
            ],
            options={
                'db_table': 'action_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary_type', models.CharField(choices=[('executive', 'Executive Summary'), ('detailed', 'Detailed Summary'), ('action_items', 'Action Items Only')], max_length=50)),
                ('content', models.TextField()),
                ('model_used', models.CharField(default='gpt-4', max_length=50)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='recordings.meetingrecording')),
            ],
            options={
                'db_table': 'meeting_summaries',
            },
        ),
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_sentiment', models.CharField(max_length=50)),
                ('sentiment_score', models.FloatField()),
                ('emotions', models.JSONField(blank=True, null=True)),
                ('engagement_score', models.FloatField(blank=True, null=True)),
                ('participation_rate', models.FloatField(blank=True, null=True)),
                ('model_used', models.CharField(default='gpt-4', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recording', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_analysis', to='recordings.meetingrecording')),
            ],
            options={
                'db_table': 'sentiment_analysis',
            },
        ),
        migrations.CreateModel(
            name='TopicDetection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('confidence', models.FloatField()),
                ('relevance_score', models.FloatField(blank=True, null=True)),
                ('start_time', models.FloatField(blank=True, null=True)),
                ('end_time', models.FloatField(blank=True, null=True)),
                ('keywords', models.JSONField(blank=True, null=True)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='recordings.meetingrecording')),
            ],
            options={
                'db_table': 'topic_detection',
                'ordering': ['-confidence'],
            },
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_text', models.TextField()),
                ('language', models.CharField(default='en', max_length=10)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('transcription_engine', models.CharField(default='whisper', max_length=50)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to='recordings.meetingrecording')),
            ],
            options={
                'db_table': 'transcriptions',
            },
        ),
        migrations.CreateModel(
            name='TranscriptionSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('speaker', models.CharField(blank=True, max_length=255, null=True)),
                ('speaker_confidence', models.FloatField(blank=True, null=True)),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='recordings.transcription')),
            ],
            options={
                'db_table': 'transcription_segments',
                'ordering': ['start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='meetingrecording',
            index=models.Index(fields=['meeting'], name='meeting_rec_meeting_0d4211_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingrecording',
            index=models.Index(fields=['platform'], name='meeting_rec_platfor_30c622_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingrecording',
            index=models.Index(fields=['status'], name='meeting_rec_status_02bbc1_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingrecording',
            index=models.Index(fields=['started_at'], name='meeting_rec_started_dc1fef_idx'),
        ),
        migrations.AddIndex(
            model_name='actionitem',
            index=models.Index(fields=['assigned_to'], name='action_item_assigne_74136a_idx'),
        ),
        migrations.AddIndex(
            model_name='actionitem',
            index=models.Index(fields=['status'], name='action_item_status_fd33af_idx'),
        ),
        migrations.AddIndex(
            model_name='actionitem',
            index=models.Index(fields=['due_date'], name='action_item_due_dat_5ab63a_idx'),
        ),
    ]
