# Generated by Django 6.0.3 on 2026-04-16 17:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordingSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zoom_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('zoom_api_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('zoom_webhook_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('teams_tenant_id', models.CharField(blank=True, max_length=255, null=True)),
                ('teams_client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('teams_client_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('openai_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('openai_organization', models.CharField(blank=True, max_length=255, null=True)),
                ('storage_type', models.CharField(choices=[('local', 'Local Storage'), ('s3', 'AWS S3'), ('gcs', 'Google Cloud Storage')], default='local', max_length=50)),
                ('aws_access_key_id', models.CharField(blank=True, max_length=255, null=True)),
                ('aws_secret_access_key', models.CharField(blank=True, max_length=255, null=True)),
                ('aws_bucket_name', models.CharField(blank=True, max_length=255, null=True)),
                ('aws_region', models.CharField(default='us-east-1', max_length=50)),
                ('gcs_project_id', models.CharField(blank=True, max_length=255, null=True)),
                ('gcs_bucket_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gcs_credentials', models.TextField(blank=True, null=True)),
                ('auto_transcribe_enabled', models.BooleanField(default=True)),
                ('auto_summarize_enabled', models.BooleanField(default=True)),
                ('auto_detect_topics', models.BooleanField(default=True)),
                ('auto_analyze_sentiment', models.BooleanField(default=True)),
                ('transcription_language', models.CharField(default='en', max_length=10)),
                ('transcription_model', models.CharField(default='whisper-1', max_length=50)),
                ('summary_model', models.CharField(default='gpt-4', max_length=50)),
                ('summary_type', models.CharField(choices=[('executive', 'Executive Summary'), ('detailed', 'Detailed Summary'), ('both', 'Both')], default='both', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recording Settings',
                'verbose_name_plural': 'Recording Settings',
                'db_table': 'recording_settings',
            },
        ),
    ]
