# Generated by Django 6.0.3 on 2026-04-16 20:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentcomment_documentshare_documenttag_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('policy_type', models.CharField(choices=[('category', 'By Category'), ('tag', 'By Tag'), ('document_type', 'By Document Type'), ('custom', 'Custom Criteria')], default='category', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('retention_period_days', models.PositiveIntegerField(help_text='Number of days to retain documents')),
                ('retention_period_years', models.PositiveIntegerField(default=0, help_text='Number of years to retain documents')),
                ('retention_action', models.CharField(choices=[('archive', 'Archive'), ('delete', 'Delete'), ('move_to_storage', 'Move to Long-term Storage')], default='archive', max_length=30)),
                ('apply_to_tags', models.JSONField(blank=True, help_text='List of tags to apply policy to', null=True)),
                ('custom_criteria', models.JSONField(blank=True, help_text='Custom filtering criteria', null=True)),
                ('apply_immediately', models.BooleanField(default=False, help_text='Apply policy immediately to existing documents')),
                ('next_run_date', models.DateTimeField(blank=True, null=True)),
                ('compliance_framework', models.CharField(blank=True, help_text='e.g., GDPR, SOX, HIPAA', max_length=100)),
                ('legal_hold', models.BooleanField(default=False, help_text='Documents on legal hold are exempt')),
                ('notify_before_action', models.BooleanField(default=True)),
                ('notify_days_before', models.PositiveIntegerField(default=30, help_text='Days before action to notify')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_applied_at', models.DateTimeField(blank=True, null=True)),
                ('apply_to_categories', models.ManyToManyField(blank=True, related_name='retention_policies', to='documents.documentcategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_retention_policies', to=settings.AUTH_USER_MODEL)),
                ('notify_users', models.ManyToManyField(blank=True, related_name='retention_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Retention Policy',
                'verbose_name_plural': 'Retention Policies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArchiveRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archive_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('restored', 'Restored')], default='pending', max_length=20)),
                ('archive_location', models.CharField(blank=True, help_text='Storage location of archived document', max_length=500)),
                ('archive_size', models.PositiveIntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the archive can be permanently deleted', null=True)),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_documents', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_records', to='documents.document')),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_archives', to=settings.AUTH_USER_MODEL)),
                ('retention_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_records', to='documents.retentionpolicy')),
            ],
            options={
                'verbose_name': 'Archive Record',
                'verbose_name_plural': 'Archive Records',
                'ordering': ['-archived_at'],
            },
        ),
        migrations.AddIndex(
            model_name='retentionpolicy',
            index=models.Index(fields=['status', '-created_at'], name='documents_r_status_5d89ba_idx'),
        ),
        migrations.AddIndex(
            model_name='retentionpolicy',
            index=models.Index(fields=['policy_type'], name='documents_r_policy__59d0ea_idx'),
        ),
        migrations.AddIndex(
            model_name='retentionpolicy',
            index=models.Index(fields=['next_run_date'], name='documents_r_next_ru_5d6f45_idx'),
        ),
        migrations.AddIndex(
            model_name='archiverecord',
            index=models.Index(fields=['archive_status', '-archived_at'], name='documents_a_archive_21be77_idx'),
        ),
        migrations.AddIndex(
            model_name='archiverecord',
            index=models.Index(fields=['document'], name='documents_a_documen_8bc421_idx'),
        ),
        migrations.AddIndex(
            model_name='archiverecord',
            index=models.Index(fields=['retention_policy'], name='documents_a_retenti_d39a4c_idx'),
        ),
        migrations.AddIndex(
            model_name='archiverecord',
            index=models.Index(fields=['expires_at'], name='documents_a_expires_cdaf30_idx'),
        ),
    ]
