# Generated by Django 6.0.3 on 2026-04-16 16:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarConfigurator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('source_app', models.CharField(max_length=50)),
                ('source_model', models.CharField(max_length=50)),
                ('title_field', models.CharField(max_length=100)),
                ('description_field', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date_field', models.CharField(max_length=100)),
                ('end_date_field', models.CharField(blank=True, max_length=100, null=True)),
                ('all_day_field', models.CharField(blank=True, max_length=100, null=True)),
                ('user_field', models.CharField(blank=True, max_length=100, null=True)),
                ('location_field', models.CharField(blank=True, max_length=100, null=True)),
                ('status_field', models.CharField(blank=True, max_length=100, null=True)),
                ('event_type', models.CharField(choices=[('meeting', 'Meeting'), ('voting_deadline', 'Voting Deadline'), ('document_due', 'Document Due Date'), ('risk_review', 'Risk Review'), ('audit_date', 'Audit Date'), ('committee_meeting', 'Committee Meeting'), ('discussion_event', 'Discussion Event'), ('esignature_deadline', 'E-Signature Deadline'), ('other', 'Other')], default='other', max_length=50)),
                ('color', models.CharField(default='#7dc143', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('filter_condition', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'calendar_configurators',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserCalendarPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_view', models.CharField(choices=[('month', 'Month'), ('week', 'Week'), ('day', 'Day'), ('agenda', 'Agenda')], default='month', max_length=20)),
                ('show_event_types', models.JSONField(default=list)),
                ('show_my_events_only', models.BooleanField(default=False)),
                ('start_of_week', models.IntegerField(default=0)),
                ('show_weekends', models.BooleanField(default=True)),
                ('email_reminders', models.BooleanField(default=True)),
                ('reminder_hours_before', models.IntegerField(default=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_calendar_preferences',
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('meeting', 'Meeting'), ('voting_deadline', 'Voting Deadline'), ('document_due', 'Document Due Date'), ('risk_review', 'Risk Review'), ('audit_date', 'Audit Date'), ('committee_meeting', 'Committee Meeting'), ('discussion_event', 'Discussion Event'), ('esignature_deadline', 'E-Signature Deadline'), ('other', 'Other')], max_length=50)),
                ('source_app', models.CharField(max_length=50)),
                ('source_model', models.CharField(max_length=50)),
                ('source_object_id', models.UUIDField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(default='#7dc143', max_length=7)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calendar_events',
                'ordering': ['start_date'],
                'indexes': [models.Index(fields=['start_date'], name='calendar_ev_start_d_8d0c20_idx'), models.Index(fields=['event_type'], name='calendar_ev_event_t_25cdb4_idx'), models.Index(fields=['source_app', 'source_object_id'], name='calendar_ev_source__695375_idx'), models.Index(fields=['user'], name='calendar_ev_user_id_42d7af_idx')],
            },
        ),
    ]
