# Generated by Django 6.0.3 on 2026-04-16 20:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCalendarConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google', 'Google Calendar'), ('outlook', 'Microsoft Outlook'), ('office365', 'Office 365'), ('exchange', 'Microsoft Exchange')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disconnected', 'Disconnected'), ('error', 'Error'), ('revoked', 'Access Revoked')], default='active', max_length=20)),
                ('access_token', models.TextField(blank=True, help_text='OAuth access token (encrypted)')),
                ('refresh_token', models.TextField(blank=True, help_text='OAuth refresh token (encrypted)')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('external_calendar_id', models.CharField(blank=True, help_text='External calendar ID', max_length=255)),
                ('calendar_name', models.CharField(blank=True, help_text='Name of the external calendar', max_length=255)),
                ('calendar_color', models.CharField(blank=True, help_text='Calendar color hex code', max_length=7)),
                ('sync_direction', models.CharField(choices=[('bidirectional', 'Bidirectional'), ('to_external', 'To External Only'), ('from_external', 'From External Only')], default='bidirectional', max_length=20)),
                ('auto_sync', models.BooleanField(default=True, help_text='Automatically sync events')),
                ('sync_interval_minutes', models.PositiveIntegerField(default=30, help_text='Sync interval in minutes')),
                ('sync_meeting_events', models.BooleanField(default=True)),
                ('sync_voting_events', models.BooleanField(default=True)),
                ('sync_document_events', models.BooleanField(default=True)),
                ('sync_other_events', models.BooleanField(default=False)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, max_length=50)),
                ('last_sync_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'External Calendar Connection',
                'verbose_name_plural': 'External Calendar Connections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalendarSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=20)),
                ('events_synced_to_external', models.PositiveIntegerField(default=0)),
                ('events_synced_from_external', models.PositiveIntegerField(default=0)),
                ('events_updated', models.PositiveIntegerField(default=0)),
                ('events_created', models.PositiveIntegerField(default=0)),
                ('events_deleted', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('error_details', models.JSONField(blank=True, null=True)),
                ('sync_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='calendar.externalcalendarconnection')),
            ],
            options={
                'verbose_name': 'Calendar Sync Log',
                'verbose_name_plural': 'Calendar Sync Logs',
                'ordering': ['-synced_at'],
            },
        ),
        migrations.AddIndex(
            model_name='externalcalendarconnection',
            index=models.Index(fields=['user', 'provider'], name='calendar_ex_user_id_4013f1_idx'),
        ),
        migrations.AddIndex(
            model_name='externalcalendarconnection',
            index=models.Index(fields=['status'], name='calendar_ex_status_61e307_idx'),
        ),
        migrations.AddIndex(
            model_name='externalcalendarconnection',
            index=models.Index(fields=['last_sync_at'], name='calendar_ex_last_sy_026669_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarsynclog',
            index=models.Index(fields=['connection', '-synced_at'], name='calendar_ca_connect_19ee98_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarsynclog',
            index=models.Index(fields=['sync_status', '-synced_at'], name='calendar_ca_sync_st_31cffb_idx'),
        ),
    ]
