# Generated by Django 6.0.3 on 2026-04-16 20:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_motion_allow_anonymous_motion_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voting_instructions', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('abstain', 'Abstain')], help_text='How to vote on behalf', max_length=10)),
                ('custom_instructions', models.TextField(blank=True, help_text='Additional instructions for the proxy')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('executed', models.BooleanField(default=False, help_text='Whether the proxy vote was executed')),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('valid_from', models.DateTimeField(help_text='When the proxy becomes valid')),
                ('valid_until', models.DateTimeField(help_text='When the proxy expires')),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='proxy_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_proxies', to=settings.AUTH_USER_MODEL)),
                ('motion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_votes', to='voting.motion')),
                ('principal', models.ForeignKey(help_text='Board member giving proxy', on_delete=django.db.models.deletion.CASCADE, related_name='given_proxies', to=settings.AUTH_USER_MODEL)),
                ('proxy', models.ForeignKey(help_text='Board member receiving proxy', on_delete=django.db.models.deletion.CASCADE, related_name='received_proxies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proxy Vote',
                'verbose_name_plural': 'Proxy Votes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['principal', '-created_at'], name='voting_prox_princip_322505_idx'), models.Index(fields=['proxy', '-created_at'], name='voting_prox_proxy_i_367f69_idx'), models.Index(fields=['motion', '-created_at'], name='voting_prox_motion__0c7fa2_idx'), models.Index(fields=['status'], name='voting_prox_status_b38f59_idx')],
                'unique_together': {('principal', 'motion')},
            },
        ),
    ]
