# Generated by Django 6.0.3 on 2026-04-16 20:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentcomment_documentshare_documenttag_and_more'),
        ('voting', '0003_proxyvote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionDocumentation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision_summary', models.TextField(help_text='Summary of the decision made')),
                ('decision_rationale', models.TextField(help_text='Rationale behind the decision')),
                ('legal_basis', models.TextField(blank=True, help_text='Legal basis or authority for the decision')),
                ('compliance_status', models.CharField(choices=[('pending_review', 'Pending Review'), ('compliant', 'Compliant'), ('non_compliant', 'Non-Compliant'), ('requires_action', 'Requires Action')], default='pending_review', max_length=20)),
                ('compliance_notes', models.TextField(blank=True, help_text='Notes on compliance review')),
                ('legal_review_date', models.DateTimeField(blank=True, null=True)),
                ('applicable_regulations', models.TextField(blank=True, help_text='List of applicable regulations and laws')),
                ('regulatory_references', models.JSONField(blank=True, help_text='Structured regulatory references', null=True)),
                ('minutes_reference', models.TextField(blank=True, help_text='Reference to meeting minutes')),
                ('implementation_plan', models.TextField(blank=True, help_text='Plan for implementing the decision')),
                ('implementation_deadline', models.DateField(blank=True, null=True)),
                ('implemented', models.BooleanField(default=False)),
                ('implemented_date', models.DateField(blank=True, null=True)),
                ('risk_assessment', models.TextField(blank=True, help_text='Risk assessment for the decision')),
                ('mitigation_measures', models.TextField(blank=True, help_text='Mitigation measures for identified risks')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_decisions', to=settings.AUTH_USER_MODEL)),
                ('documented_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documented_decisions', to=settings.AUTH_USER_MODEL)),
                ('motion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision_documentation', to='voting.motion')),
                ('reviewed_by_legal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_reviews', to=settings.AUTH_USER_MODEL)),
                ('supporting_documents', models.ManyToManyField(blank=True, related_name='decisions', to='documents.document')),
            ],
            options={
                'verbose_name': 'Decision Documentation',
                'verbose_name_plural': 'Decision Documentations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['motion'], name='voting_deci_motion__a4b06c_idx'), models.Index(fields=['compliance_status'], name='voting_deci_complia_42666a_idx'), models.Index(fields=['legal_review_date'], name='voting_deci_legal_r_239442_idx')],
            },
        ),
    ]
