# Generated by Django 6.0.3 on 2026-04-16 20:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentcomment_documentshare_documenttag_and_more'),
        ('voting', '0004_decisiondocumentation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motion_title', models.CharField(max_length=200)),
                ('motion_category', models.CharField(max_length=20)),
                ('vote_choice', models.CharField(max_length=20)),
                ('voting_session_date', models.DateTimeField()),
                ('meeting_title', models.CharField(blank=True, max_length=200)),
                ('motion_outcome', models.CharField(help_text='Final outcome of the motion', max_length=20)),
                ('vote_weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('was_decisive_vote', models.BooleanField(default=False, help_text='Whether this vote was decisive')),
                ('aligned_with_majority', models.BooleanField(default=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Voting History',
                'verbose_name_plural': 'Voting History',
                'ordering': ['-voting_session_date'],
            },
        ),
        migrations.CreateModel(
            name='VotingPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_votes', models.PositiveIntegerField(default=0)),
                ('votes_in_favor', models.PositiveIntegerField(default=0)),
                ('votes_against', models.PositiveIntegerField(default=0)),
                ('abstentions', models.PositiveIntegerField(default=0)),
                ('consistency_score', models.DecimalField(blank=True, decimal_places=2, help_text='Voting consistency score (0-100)', max_digits=5, null=True)),
                ('category_breakdown', models.JSONField(blank=True, null=True)),
                ('participation_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of motions voted on', max_digits=5)),
                ('total_eligible_votes', models.PositiveIntegerField(default=0)),
                ('typically_votes_with_majority', models.BooleanField(default=True)),
                ('often_abstains', models.BooleanField(default=False)),
                ('frequently_dissents', models.BooleanField(default=False)),
                ('last_calculated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Voting Pattern',
                'verbose_name_plural': 'Voting Patterns',
                'ordering': ['-last_calculated_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='decisiondocumentation',
            name='voting_deci_legal_r_239442_idx',
        ),
        migrations.AddField(
            model_name='decisiondocumentation',
            name='compliance_score',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='decisiondocumentation',
            name='implementation_status',
            field=models.CharField(blank=True, help_text='Current implementation status', max_length=50),
        ),
        migrations.AlterField(
            model_name='decisiondocumentation',
            name='compliance_notes',
            field=models.TextField(blank=True, help_text='Notes on compliance considerations'),
        ),
        migrations.AlterField(
            model_name='decisiondocumentation',
            name='compliance_status',
            field=models.CharField(choices=[('compliant', 'Compliant'), ('non_compliant', 'Non-Compliant'), ('partially_compliant', 'Partially Compliant'), ('pending_review', 'Pending Review')], default='pending_review', max_length=30),
        ),
        migrations.AlterField(
            model_name='decisiondocumentation',
            name='decision_summary',
            field=models.TextField(help_text='Summary of the decision'),
        ),
        migrations.AlterField(
            model_name='decisiondocumentation',
            name='legal_basis',
            field=models.TextField(help_text='Legal basis for the decision'),
        ),
        migrations.AlterField(
            model_name='decisiondocumentation',
            name='supporting_documents',
            field=models.ManyToManyField(blank=True, related_name='decision_documentations', to='documents.document'),
        ),
        migrations.AddField(
            model_name='votinghistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='votinghistory',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='voting.vote'),
        ),
        migrations.AddField(
            model_name='votingpattern',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_patterns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='decisiondocumentation',
            name='applicable_regulations',
        ),
        migrations.RemoveField(
            model_name='decisiondocumentation',
            name='decision_rationale',
        ),
        migrations.RemoveField(
            model_name='decisiondocumentation',
            name='documented_by',
        ),
        migrations.RemoveField(
            model_name='decisiondocumentation',
            name='implemented',
        ),
        migrations.RemoveField(
            model_name='decisiondocumentation',
            name='implemented_date',
        ),
        migrations.RemoveField(
            model_name='decisiondocumentation',
            name='legal_review_date',
        ),
        migrations.RemoveField(
            model_name='decisiondocumentation',
            name='minutes_reference',
        ),
        migrations.RemoveField(
            model_name='decisiondocumentation',
            name='mitigation_measures',
        ),
        migrations.RemoveField(
            model_name='decisiondocumentation',
            name='regulatory_references',
        ),
        migrations.RemoveField(
            model_name='decisiondocumentation',
            name='reviewed_by_legal',
        ),
        migrations.RemoveField(
            model_name='decisiondocumentation',
            name='risk_assessment',
        ),
        migrations.AddIndex(
            model_name='votinghistory',
            index=models.Index(fields=['user', '-voting_session_date'], name='voting_voti_user_id_2d3e16_idx'),
        ),
        migrations.AddIndex(
            model_name='votinghistory',
            index=models.Index(fields=['motion_category'], name='voting_voti_motion__eec23a_idx'),
        ),
        migrations.AddIndex(
            model_name='votinghistory',
            index=models.Index(fields=['vote_choice'], name='voting_voti_vote_ch_f0eb74_idx'),
        ),
        migrations.AddIndex(
            model_name='votinghistory',
            index=models.Index(fields=['-voting_session_date'], name='voting_voti_voting__2064b1_idx'),
        ),
        migrations.AddIndex(
            model_name='votingpattern',
            index=models.Index(fields=['user', '-last_calculated_at'], name='voting_voti_user_id_1ec8ff_idx'),
        ),
        migrations.AddIndex(
            model_name='votingpattern',
            index=models.Index(fields=['-participation_rate'], name='voting_voti_partici_320a85_idx'),
        ),
    ]
