# Generated by Django 6.0.3 on 2026-04-16 21:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0010_boardpack_boardpackaccesslog_and_more'),
        ('voting', '0005_votinghistory_votingpattern_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuorumTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('required_members', models.IntegerField(help_text='Number of members required for quorum')),
                ('present_members', models.IntegerField(help_text='Number of members present')),
                ('status', models.CharField(choices=[('not_met', 'Quorum Not Met'), ('met', 'Quorum Met'), ('lost', 'Quorum Lost'), ('waived', 'Quorum Waived')], default='not_met', max_length=20)),
                ('quorum_met_at', models.DateTimeField(blank=True, help_text='When quorum was first met', null=True)),
                ('quorum_lost_at', models.DateTimeField(blank=True, help_text='When quorum was lost', null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quorum_records', to='meetings.meeting')),
                ('voting_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quorum_records', to='voting.votingsession')),
            ],
            options={
                'verbose_name': 'Quorum Tracking',
                'verbose_name_plural': 'Quorum Tracking',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['meeting', '-checked_at'], name='voting_quor_meeting_e47933_idx'), models.Index(fields=['voting_session', '-checked_at'], name='voting_quor_voting__aa37b3_idx'), models.Index(fields=['status'], name='voting_quor_status_3417fc_idx')],
            },
        ),
    ]
