# Generated by Django 6.0.3 on 2026-04-16 21:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('meetings', '0010_boardpack_boardpackaccesslog_and_more'),
        ('voting', '0005_votinghistory_votingpattern_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attended', models.BooleanField(default=True)),
                ('arrived_late', models.BooleanField(default=False)),
                ('left_early', models.BooleanField(default=False)),
                ('participation_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('questions_asked', models.PositiveIntegerField(default=0)),
                ('comments_made', models.PositiveIntegerField(default=0)),
                ('documents_reviewed', models.PositiveIntegerField(default=0)),
                ('meeting_duration', models.DurationField(blank=True, null=True)),
                ('attendance_duration', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Attendance Analytics',
                'verbose_name_plural': 'Attendance Analytics',
                'ordering': ['-meeting__scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceScorecard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('overall_score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('compliant', 'Compliant'), ('non_compliant', 'Non-Compliant'), ('partially_compliant', 'Partially Compliant'), ('not_applicable', 'Not Applicable')], max_length=20)),
                ('governance_score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('financial_score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('operational_score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('findings', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compliance Scorecard',
                'verbose_name_plural': 'Compliance Scorecards',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='CustomReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('summary', 'Summary Report'), ('detailed', 'Detailed Report'), ('comparative', 'Comparative Report'), ('trend', 'Trend Analysis')], max_length=20)),
                ('data_sources', models.JSONField(blank=True, default=list, help_text='List of data sources for the report')),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Filter configuration')),
                ('groupings', models.JSONField(blank=True, default=list, help_text='Grouping configuration')),
                ('calculations', models.JSONField(blank=True, default=list, help_text='Calculations to perform')),
                ('schedule', models.CharField(blank=True, help_text='Cron-like schedule', max_length=50)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('output_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('generated_file', models.FileField(blank=True, null=True, upload_to='reports/custom/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Custom Report',
                'verbose_name_plural': 'Custom Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DecisionTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('decision_type', models.CharField(choices=[('strategic', 'Strategic Decision'), ('operational', 'Operational Decision'), ('financial', 'Financial Decision'), ('governance', 'Governance Decision'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('outcome', models.TextField(blank=True, help_text='Final outcome of the decision')),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('implementation_date', models.DateField(blank=True, null=True)),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('impact_description', models.TextField(blank=True)),
                ('success_metrics', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Decision Tracking',
                'verbose_name_plural': 'Decision Tracking',
                'ordering': ['-decision_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='analyticsreport',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='analyticsreport',
            name='analytics_a_report__6da31a_idx',
        ),
        migrations.RemoveIndex(
            model_name='analyticsreport',
            name='analytics_a_status_8de32c_idx',
        ),
        migrations.AddField(
            model_name='attendanceanalytics',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_analytics', to='meetings.meeting'),
        ),
        migrations.AddField(
            model_name='attendanceanalytics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancescorecard',
            name='reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_scorecards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customreport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decisiontracking',
            name='decision_maker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decisiontracking',
            name='implementer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_implemented', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decisiontracking',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='meetings.meeting'),
        ),
        migrations.AddField(
            model_name='decisiontracking',
            name='motion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='voting.motion'),
        ),
        migrations.RemoveField(
            model_name='analyticsreport',
            name='updated_at',
        ),
        migrations.AlterUniqueTogether(
            name='attendanceanalytics',
            unique_together={('meeting', 'user')},
        ),
    ]
