# Generated by Django 6.0.3 on 2026-04-16 19:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('gdpr', 'GDPR'), ('data_protection', 'Data Protection'), ('financial', 'Financial Regulation'), ('governance', 'Corporate Governance'), ('health_safety', 'Health & Safety'), ('environmental', 'Environmental'), ('employment', 'Employment Law'), ('tax', 'Tax Compliance'), ('reporting', 'Reporting Requirements'), ('other', 'Other')], max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Regulation reference number', max_length=50)),
                ('status', models.CharField(choices=[('compliant', 'Compliant'), ('non_compliant', 'Non-Compliant'), ('partially_compliant', 'Partially Compliant'), ('not_applicable', 'Not Applicable')], default='partially_compliant', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('effective_date', models.DateField(help_text='When this requirement became effective')),
                ('review_date', models.DateField(help_text='Next review date')),
                ('compliance_score', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compliance_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_requirements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compliance Requirement',
                'verbose_name_plural': 'Compliance Requirements',
                'ordering': ['priority', '-compliance_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('audit_date', models.DateField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('findings', 'Findings Identified'), ('remediation', 'Remediation Required')], default='scheduled', max_length=20)),
                ('score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('findings', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('remediation_plan', models.TextField(blank=True)),
                ('remediation_due_date', models.DateField(blank=True, null=True)),
                ('remediation_completed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auditor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_audits', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ManyToManyField(blank=True, related_name='reviewed_audits', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='risk.compliancerequirement')),
            ],
            options={
                'verbose_name': 'Compliance Audit',
                'verbose_name_plural': 'Compliance Audits',
                'ordering': ['-audit_date'],
            },
        ),
    ]
