# Generated by Django 6.0.3 on 2026-04-16 19:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_meetingaction_reminder_count_and_more'),
        ('risk', '0002_compliancerequirement_complianceaudit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictOfInterestDeclaration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the conflict of interest')),
                ('conflict_type', models.CharField(help_text='Type of conflict (e.g., financial, personal, business)', max_length=100)),
                ('related_entity', models.CharField(blank=True, help_text='Name of related entity or individual', max_length=200)),
                ('relationship_nature', models.TextField(blank=True, help_text='Nature of the relationship')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('mitigated', 'Mitigated'), ('escalated', 'Escalated')], default='pending', max_length=20)),
                ('mitigation_plan', models.TextField(blank=True, help_text='Plan to mitigate the conflict')),
                ('mitigation_approved_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('declared_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('declarant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coi_declarations', to=settings.AUTH_USER_MODEL)),
                ('mitigation_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_mitigations', to=settings.AUTH_USER_MODEL)),
                ('related_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coi_declarations', to='meetings.meeting')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_coi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conflict of Interest Declaration',
                'verbose_name_plural': 'Conflict of Interest Declarations',
                'ordering': ['-declared_at'],
                'indexes': [models.Index(fields=['declarant', '-declared_at'], name='risk_confli_declara_b71c03_idx'), models.Index(fields=['status', '-declared_at'], name='risk_confli_status_1577b9_idx'), models.Index(fields=['severity', '-declared_at'], name='risk_confli_severit_64d0ae_idx')],
            },
        ),
    ]
