# Generated by Django 6.0.3 on 2026-04-16 19:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0003_conflictofinterestdeclaration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhistleblowerReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('fraud', 'Fraud'), ('corruption', 'Corruption'), ('harassment', 'Harassment'), ('discrimination', 'Discrimination'), ('safety', 'Safety Violation'), ('environmental', 'Environmental Concern'), ('financial', 'Financial Irregularity'), ('governance', 'Governance Issue'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the concern')),
                ('is_anonymous', models.BooleanField(default=True)),
                ('reporter_email', models.EmailField(blank=True, help_text='Optional email for follow-up (if not fully anonymous)', max_length=254)),
                ('reporter_phone', models.CharField(blank=True, help_text='Optional phone for follow-up (if not fully anonymous)', max_length=20)),
                ('incident_date', models.DateField(blank=True, help_text='Date of the incident', null=True)),
                ('location', models.CharField(blank=True, help_text='Location of the incident', max_length=200)),
                ('individuals_involved', models.TextField(blank=True, help_text='Names of individuals involved (if known)')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('unfounded', 'Unfounded'), ('closed', 'Closed')], default='submitted', max_length=20)),
                ('attachments', models.JSONField(blank=True, help_text='List of attached file IDs', null=True)),
                ('investigation_notes', models.TextField(blank=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Whistleblower Report',
                'verbose_name_plural': 'Whistleblower Reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='risk_whistl_status_8a9536_idx'), models.Index(fields=['severity', '-created_at'], name='risk_whistl_severit_6c6e69_idx'), models.Index(fields=['category', '-created_at'], name='risk_whistl_categor_8970b9_idx')],
            },
        ),
    ]
