# Generated by Django 6.0.3 on 2026-04-16 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentcomment_documentshare_documenttag_and_more'),
        ('risk', '0004_whistleblowerreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancerequirement',
            name='data_processing_purpose',
            field=models.TextField(blank=True, help_text='Purpose of data processing'),
        ),
        migrations.AddField(
            model_name='compliancerequirement',
            name='data_subject_rights',
            field=models.TextField(blank=True, help_text='Data subject rights addressed'),
        ),
        migrations.AddField(
            model_name='compliancerequirement',
            name='evidence_documents',
            field=models.ManyToManyField(blank=True, related_name='compliance_evidence', to='documents.document'),
        ),
        migrations.AddField(
            model_name='compliancerequirement',
            name='gdpr_article',
            field=models.CharField(blank=True, help_text='GDPR Article number if applicable', max_length=20),
        ),
        migrations.AddField(
            model_name='compliancerequirement',
            name='jurisdiction',
            field=models.CharField(blank=True, help_text='Applicable jurisdiction/country', max_length=100),
        ),
        migrations.AddField(
            model_name='compliancerequirement',
            name='lawful_basis',
            field=models.CharField(blank=True, help_text='Lawful basis for processing', max_length=100),
        ),
        migrations.AddField(
            model_name='compliancerequirement',
            name='local_law_reference',
            field=models.TextField(blank=True, help_text='References to local laws and regulations'),
        ),
        migrations.AddField(
            model_name='compliancerequirement',
            name='policy_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_policies', to='documents.document'),
        ),
    ]
