# Generated by Django 6.0.3 on 2026-04-16 20:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentcomment_documentshare_documenttag_and_more'),
        ('risk', '0005_compliancerequirement_data_processing_purpose_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evaluation_type', models.CharField(choices=[('annual', 'Annual Evaluation'), ('quarterly', 'Quarterly Review'), ('special', 'Special Evaluation'), ('self_assessment', 'Self-Assessment')], max_length=20)),
                ('evaluation_period_start', models.DateField(help_text='Start date of evaluation period')),
                ('evaluation_period_end', models.DateField(help_text='End date of evaluation period')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('reviewed', 'Reviewed'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('overall_score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('overall_rating', models.CharField(blank=True, help_text='Overall rating (e.g., Excellent, Good, Needs Improvement)', max_length=20)),
                ('summary', models.TextField(help_text='Executive summary of the evaluation')),
                ('strengths', models.TextField(blank=True, help_text='Board strengths identified')),
                ('areas_for_improvement', models.TextField(blank=True, help_text='Areas requiring improvement')),
                ('recommendations', models.TextField(blank=True, help_text='Recommendations for improvement')),
                ('governance_effectiveness', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('strategic_oversight', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('risk_management', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('composition_assessment', models.TextField(blank=True, help_text='Assessment of board composition and diversity')),
                ('independence_assessment', models.TextField(blank=True, help_text='Assessment of board independence')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_board_evaluations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_board_evaluations', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_board_evaluations', to=settings.AUTH_USER_MODEL)),
                ('supporting_documents', models.ManyToManyField(blank=True, related_name='board_evaluations', to='documents.document')),
            ],
            options={
                'verbose_name': 'Board Evaluation',
                'verbose_name_plural': 'Board Evaluations',
                'ordering': ['-evaluation_period_end'],
            },
        ),
        migrations.CreateModel(
            name='DirectorEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('self_rating', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('satisfactory', 'Satisfactory'), ('needs_improvement', 'Needs Improvement'), ('unsatisfactory', 'Unsatisfactory')], max_length=20)),
                ('self_assessment', models.TextField(blank=True, help_text="Director's self-assessment")),
                ('peer_rating', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('satisfactory', 'Satisfactory'), ('needs_improvement', 'Needs Improvement'), ('unsatisfactory', 'Unsatisfactory')], max_length=20)),
                ('peer_feedback', models.TextField(blank=True, help_text='Peer feedback summary')),
                ('chair_rating', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('satisfactory', 'Satisfactory'), ('needs_improvement', 'Needs Improvement'), ('unsatisfactory', 'Unsatisfactory')], max_length=20)),
                ('chair_feedback', models.TextField(blank=True, help_text="Board chair's feedback")),
                ('overall_rating', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('satisfactory', 'Satisfactory'), ('needs_improvement', 'Needs Improvement'), ('unsatisfactory', 'Unsatisfactory')], max_length=20)),
                ('overall_score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('governance_knowledge', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('strategic_thinking', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('financial_literacy', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('industry_expertise', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('communication', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('participation', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('development_needs', models.TextField(blank=True, help_text='Identified development needs')),
                ('training_recommendations', models.TextField(blank=True, help_text='Training and development recommendations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='director_evaluations', to='risk.boardevaluation')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Director Evaluation',
                'verbose_name_plural': 'Director Evaluations',
                'ordering': ['board_evaluation', 'director'],
            },
        ),
        migrations.AddIndex(
            model_name='boardevaluation',
            index=models.Index(fields=['evaluation_type', '-evaluation_period_end'], name='risk_boarde_evaluat_eaa97b_idx'),
        ),
        migrations.AddIndex(
            model_name='boardevaluation',
            index=models.Index(fields=['status'], name='risk_boarde_status_3b31bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='directorevaluation',
            unique_together={('board_evaluation', 'director')},
        ),
    ]
