# Generated by Django 6.0.3 on 2026-04-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_meetingaction_alter_meetingattendance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='auto_summarize',
            field=models.BooleanField(default=False, help_text='Automatically generate meeting summaries using AI'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='auto_transcribe',
            field=models.BooleanField(default=False, help_text='Automatically transcribe meeting recordings using AI'),
        ),
    ]
