# Generated by Django 6.0.3 on 2026-04-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_meeting_auto_summarize_meeting_auto_transcribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingaction',
            name='reminder_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meetingaction',
            name='reminder_frequency',
            field=models.CharField(choices=[('none', 'No Reminders'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('bi_weekly', 'Bi-Weekly')], default='weekly', max_length=20),
        ),
        migrations.AddField(
            model_name='meetingaction',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
