# Generated by Django 6.0.3 on 2026-04-16 20:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_meetingaction_reminder_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuorumCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('attendees_present', models.PositiveIntegerField(help_text='Number of attendees present')),
                ('quorum_met', models.BooleanField(help_text='Whether quorum was met at time of check')),
                ('quorum_required', models.PositiveIntegerField(help_text='Quorum requirement at time of check')),
                ('notes', models.TextField(blank=True, help_text='Notes about the quorum check')),
                ('attendees_list', models.ManyToManyField(blank=True, related_name='quorum_attendances', to=settings.AUTH_USER_MODEL)),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quorum_checks', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quorum_checks', to='meetings.meeting')),
            ],
            options={
                'verbose_name': 'Quorum Check',
                'verbose_name_plural': 'Quorum Checks',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['meeting', '-checked_at'], name='meetings_qu_meeting_0472a0_idx'), models.Index(fields=['checked_by', '-checked_at'], name='meetings_qu_checked_1aee12_idx')],
            },
        ),
    ]
