# Generated by Django 6.0.3 on 2026-04-16 20:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentcomment_documentshare_documenttag_and_more'),
        ('meetings', '0007_quorumcheck'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment_type', models.CharField(choices=[('suggestion', 'Suggestion'), ('question', 'Question'), ('clarification', 'Clarification'), ('approval', 'Approval'), ('concern', 'Concern'), ('general', 'General Comment')], default='general', max_length=20)),
                ('content', models.TextField(help_text='Comment content')),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes on how the comment was resolved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agenda_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='meetings.agendaitem')),
                ('attachments', models.ManyToManyField(blank=True, related_name='agenda_comments', to='documents.document')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='meetings.agendacomment')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_agenda_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agenda Comment',
                'verbose_name_plural': 'Agenda Comments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agenda_item', '-created_at'], name='meetings_ag_agenda__65eecf_idx'), models.Index(fields=['author', '-created_at'], name='meetings_ag_author__9cb380_idx'), models.Index(fields=['resolved'], name='meetings_ag_resolve_948bff_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgendaSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(help_text='Field being modified (e.g., title, description)', max_length=100)),
                ('original_value', models.TextField(help_text='Original value')),
                ('suggested_value', models.TextField(help_text='Suggested new value')),
                ('reason', models.TextField(help_text='Reason for the suggestion')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('deferred', 'Deferred')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Notes on the review decision')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agenda_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='meetings.agendaitem')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_agenda_suggestions', to=settings.AUTH_USER_MODEL)),
                ('suggested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agenda Suggestion',
                'verbose_name_plural': 'Agenda Suggestions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agenda_item', '-created_at'], name='meetings_ag_agenda__1d5024_idx'), models.Index(fields=['suggested_by', '-created_at'], name='meetings_ag_suggest_745ffc_idx'), models.Index(fields=['status'], name='meetings_ag_status_7abf17_idx')],
            },
        ),
    ]
