# Generated by Django 6.0.3 on 2026-04-16 20:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_agendacomment_agendasuggestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingminutes',
            name='e_signature_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for collecting signatures', null=True),
        ),
        migrations.AddField(
            model_name='meetingminutes',
            name='e_signature_required',
            field=models.BooleanField(default=False, help_text='Require e-signatures for approval'),
        ),
        migrations.AddField(
            model_name='meetingminutes',
            name='e_signature_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending Signatures'), ('partial', 'Partially Signed'), ('complete', 'Fully Signed'), ('failed', 'Failed')], default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='meetingminutes',
            name='external_signature_id',
            field=models.CharField(blank=True, help_text='ID from external e-signature service', max_length=200),
        ),
        migrations.AddField(
            model_name='meetingminutes',
            name='external_signature_provider',
            field=models.CharField(blank=True, help_text='e.g., docusign, adobe_sign', max_length=50),
        ),
        migrations.AddField(
            model_name='meetingminutes',
            name='external_signature_url',
            field=models.URLField(blank=True, help_text='URL to external signature document'),
        ),
        migrations.AddField(
            model_name='meetingminutes',
            name='signatories',
            field=models.ManyToManyField(blank=True, help_text='Users who need to sign', related_name='minutes_to_sign', to=settings.AUTH_USER_MODEL),
        ),
    ]
