# Generated by Django 6.0.3 on 2026-04-16 20:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_retentionpolicy_archiverecord_and_more'),
        ('meetings', '0009_meetingminutes_e_signature_deadline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardPack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('ready', 'Ready'), ('distributed', 'Distributed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('distribution_method', models.CharField(choices=[('email', 'Email'), ('portal', 'Portal'), ('both', 'Email and Portal')], default='portal', max_length=20)),
                ('distribution_date', models.DateTimeField(blank=True, null=True)),
                ('pack_file', models.FileField(blank=True, null=True, upload_to='board_packs/')),
                ('pack_size', models.PositiveIntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('include_cover_page', models.BooleanField(default=True)),
                ('cover_title', models.CharField(blank=True, max_length=200)),
                ('cover_message', models.TextField(blank=True)),
                ('include_toc', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('send_notification', models.BooleanField(default=True)),
                ('notification_message', models.TextField(blank=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('cc_recipients', models.ManyToManyField(blank=True, related_name='cc_board_packs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_board_packs', to=settings.AUTH_USER_MODEL)),
                ('documents', models.ManyToManyField(blank=True, related_name='board_packs', to='documents.document')),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='board_pack', to='meetings.meeting')),
                ('recipients', models.ManyToManyField(blank=True, related_name='board_packs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Board Pack',
                'verbose_name_plural': 'Board Packs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BoardPackAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('viewed', 'Viewed'), ('downloaded', 'Downloaded'), ('emailed', 'Emailed')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('board_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='meetings.boardpack')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_pack_access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Board Pack Access Log',
                'verbose_name_plural': 'Board Pack Access Logs',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='boardpack',
            index=models.Index(fields=['meeting', '-created_at'], name='meetings_bo_meeting_f9ee5b_idx'),
        ),
        migrations.AddIndex(
            model_name='boardpack',
            index=models.Index(fields=['status'], name='meetings_bo_status_162f52_idx'),
        ),
        migrations.AddIndex(
            model_name='boardpack',
            index=models.Index(fields=['distribution_date'], name='meetings_bo_distrib_1487ac_idx'),
        ),
        migrations.AddIndex(
            model_name='boardpackaccesslog',
            index=models.Index(fields=['board_pack', '-accessed_at'], name='meetings_bo_board_p_cae39e_idx'),
        ),
        migrations.AddIndex(
            model_name='boardpackaccesslog',
            index=models.Index(fields=['user', '-accessed_at'], name='meetings_bo_user_id_e3a235_idx'),
        ),
        migrations.AddIndex(
            model_name='boardpackaccesslog',
            index=models.Index(fields=['action'], name='meetings_bo_action_25b00e_idx'),
        ),
    ]
